version: '3.1'

services:

  db:
    image: mysql:5.7
    container_name: sirio-db
    restart: always
    environment:
      MYSQL_DATABASE: sirio
      MYSQL_USER: sirio
      MYSQL_PASSWORD: sirio
      MYSQL_ROOT_PASSWORD: sirio
    ports:
      - '3306:3306'
    volumes:
      - .db/dbdata:/var/lib/mysql
